### ISSUE TITLE
Pull gh-pages into master

### ISSUE THREAD

**Issue by mpfl** [au-research/FAIR-data-101-training#31]
- [x] Maintain links to quiz markdown rather than surveymonkey
- [x] Remove announcements (but leave space for announcements)

**Comment by ragamouf** [comment]
Sanity check is complete! Numbered thoughts below:

1) Should each quiz.md AND/OR the reuse.md acknowledge that each quiz.md shows the correct answer/s and would need to be transposed to local quiz platform of the (re)user's choosing before it could truly function as a quiz?

2) I.e. should the following text prefacing each quiz be replaced?
Current:

> You can retake this quiz after submitting it by opening the quiz again using your unique link. You can retake the quiz as many times as you would like up until the last day of the course. Your final answers when the quiz closes will be the ones used to determine your score.
> 
> If you score greater than 50% correct in all four quizzes by the end of the course, you will receive a FAIR Data 101 sticker.

Replace with:
This file includes the quiz questions and correct answers, and is optimised for a multiple choice or multiple checkbox question format. You can use this file to migrate the questions and answers into a quiz platform of your own choosing.

3) In FINDABLE/ The quality of the webinar 1 and webinar 2 slides are imperfect. Looks like the ARDC logo on any blue background slide and a couple of metadata images in webinar 2 did not render in the pdf. Is that because the pdf/a process doesn't work on .png files? However, does this truly matter?

4) Actually, the ARDC logo problem occurs in blue slides of all presentation pdfs. Maybe this is too hard basket.

5) Add to the reuse page: "We periodically save a snapshot of this repo to Zenodo, after major updates. Please use the suggested citation from the latest version of the zenodo record if you want to cite any of these materials."

**Comment by mpfl** [comment]
Yes, yes, ARGH, ARGH, yes.

**Comment by mpfl** [comment]
Addressed 1, 2, 5. 3 and 4 out of scope for now.
